export { default as HeroSection } from "./hero";
export { default as ReviewSection } from "./review";
export { default as VideoSection } from "./video";
export { default as GallerySection } from "./gallery";
export { default as ServicesSection } from "./services";
export { default as PricingSection } from "./pricing";
export { default as AboutSoftwareSection } from "./aboutSoftware";
export { default as InquiryFormSection } from "./inquiryForm";
export { default as AboutCRMSection } from "./aboutCRM";
