import { EventTemplate } from "../types/event";

export const defaultEventsTemplateData: EventTemplate[] = [
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 1,
    slotName: "Birdal Bouquet",
    defaultArrangementType: 1,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 2,
    slotName: "Bridesmaids Bouquets",
    defaultArrangementType: 2,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 3,
    slotName: "Groom Boutonniere",
    defaultArrangementType: 3,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 4,
    slotName: "Groomsmen Boutonniere",
    defaultArrangementType: 3,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 5,
    slotName: "Fathers Boutonniere",
    defaultArrangementType: 3,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 6,
    slotName: "Officiant Boutonniere",
    defaultArrangementType: 3,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 7,
    slotName: "Extra Bridal Bouquet",
    defaultArrangementType: 1,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 8,
    slotName: "Corsages",
    defaultArrangementType: 4,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 9,
    slotName: "Mothers Corsages",
    defaultArrangementType: 4,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 10,
    slotName: "Grandmothers Corsages",
    defaultArrangementType: 4,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 11,
    slotName: "Bridal Hair",
    defaultArrangementType: 10,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 12,
    slotName: "Bridesmaids Hair",
    defaultArrangementType: 10,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 13,
    slotName: "Flower Girl Crown",
    defaultArrangementType: 16,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 14,
    slotName: "Flower Girl Basket & Petals",
    defaultArrangementType: 16,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 15,
    slotName: "Flower Girl Bouquet",
    defaultArrangementType: 2,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 16,
    slotName: "Flowers Girls Circle",
    defaultArrangementType: 16,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 17,
    slotName: "Ring Bearer",
    defaultArrangementType: 3,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 18,
    slotName: "Toss Bouquet",
    defaultArrangementType: 2,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 19,
    slotName: "Welcome Sign",
    defaultArrangementType: 19,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 20,
    slotName: "Virgin of Mary Bouquet",
    defaultArrangementType: 2,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "PERSONAL",
    slotNo: 21,
    slotName: "Maid of honor",
    defaultArrangementType: 3,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 1,
    slotName: "Arch #1",
    defaultArrangementType: 5,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 2,
    slotName: "Arch #2",
    defaultArrangementType: 5,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 3,
    slotName: "Aisle #1",
    defaultArrangementType: 6,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 4,
    slotName: "Aisle #2",
    defaultArrangementType: 6,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 5,
    slotName: "Aisle Chairs",
    defaultArrangementType: 7,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 6,
    slotName: "Cocktail Tables",
    defaultArrangementType: 20,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 7,
    slotName: "Garland #1",
    defaultArrangementType: 12,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 8,
    slotName: "Garland #2",
    defaultArrangementType: 12,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 9,
    slotName: "Elevated #1",
    defaultArrangementType: 17,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 10,
    slotName: "Elevated #2",
    defaultArrangementType: 17,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 11,
    slotName: "Short Arrangement",
    defaultArrangementType: 9,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "CEREMONY",
    slotNo: 12,
    slotName: "Tall Arrangement",
    defaultArrangementType: 8,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 1,
    slotName: "Tall Arrangement #1",
    defaultArrangementType: 8,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 2,
    slotName: "Tall Arrangement #2",
    defaultArrangementType: 8,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 3,
    slotName: "Tall Arrangement #3",
    defaultArrangementType: 8,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 4,
    slotName: "Short Arrangement #1",
    defaultArrangementType: 9,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 5,
    slotName: "Short Arrangement #2",
    defaultArrangementType: 9,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 6,
    slotName: "Short Arrangement #3",
    defaultArrangementType: 9,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 7,
    slotName: "Short Arrangement #4",
    defaultArrangementType: 9,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 8,
    slotName: "Garland #1",
    defaultArrangementType: 12,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 9,
    slotName: "Garland #2",
    defaultArrangementType: 12,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 10,
    slotName: "Elevated #1",
    defaultArrangementType: 17,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 11,
    slotName: "Elevated #2",
    defaultArrangementType: 17,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 12,
    slotName: "Seating Chart #1",
    defaultArrangementType: 19,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 13,
    slotName: "Seating Chart #2",
    defaultArrangementType: 19,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 14,
    slotName: "Choppas",
    defaultArrangementType: 14,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 15,
    slotName: "Backdrop",
    defaultArrangementType: 5,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 16,
    slotName: "Sweetheart Table",
    defaultArrangementType: 13,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 17,
    slotName: "Table Bridges",
    defaultArrangementType: 15,
    event: null,
    arrangement: null,
  },
  {
    id: null,
    eventId: null,
    arrangementId: null,
    section: "RECEPTION",
    slotNo: 18,
    slotName: "Cake Flowers",
    defaultArrangementType: 18,
    event: null,
    arrangement: null,
  },
];
